### PR TITLE
Issue #2: Align with Cloudera Director 2.4

### PR DESCRIPTION
**Pull request by takabow**
- docker-compose.yml
  - Update Cloudera Director version from 2.3 to 2.4 
  - Delete `image` section

### CODE REVIEW

**Review by tsuyo — COMMENTED** [review]
could you keep "image:" entry (but with 2.4.0)? I'll push it soon.

**Comment by takabow** [comment]
Thank you for your comment.
I fixed it.

**Comment by tsuyo** [comment]
Thanks. "image:" entry should be the same indent/level as "build:" (not under "build:"). Could you modify this once again? :)

**Comment by takabow** [comment]
Done!

**Pull request merged**
